### ISSUE TITLE
Support for SPA?

### ISSUE THREAD

**Issue by sukhcha-in** [pkasila/ReactAdsense#1]
I'm using next.js 12 and tried this plugin, it works but has issues on initial loading.

For example: when I visit example.com no ads load, but when I change the route through `next/link` it loads the ads properly.

**Comment by pkasila** [comment]
As far as I understand, you are having this issue with Next.JS when using Next.JS's `Script` component to add `adsbygoogle.js` to your page

I've tried to reproduce this behavior and indeed it behaves incorrectly when using something like:
```jsx
function MyApp({ Component, pageProps }) {
  return <>
    <Component {...pageProps} />
    <Script src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" />
  </>
}
```

But the problem is not with `ReactAdsense` but with that `adsbygoogle.js` is not loaded before being called by `ReactAdsense`. Using `strategy='beforeInteractive'` seems to fix the issue:

```jsx
function MyApp({ Component, pageProps }) {
  return <>
    <Component {...pageProps} />
    <Script strategy='beforeInteractive' src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" />
  </>
}
```

If it doesn't fix the issue, can you provide sources to test this behavior?

**Comment by sukhcha-in** [comment]
Thanks for the update, I managed to do this with:
`_app.js`:
```
<Script strategy={"afterInteractive"} src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5223874223499257" crossOrigin="anonymous" />
```
Ad component:
```
import React, { useEffect } from "react";

export default function Adsense() {
  const loadAds = () => {
    try {
      if (typeof window !== "undefined") {
        (window.adsbygoogle = window.adsbygoogle || []).push({});
      }
    } catch (error) {
      console.log("adsense error", error.message);
    }
  };

  useEffect(() => {
    loadAds();
  }, []);

  return (
    <ins
      className="adsbygoogle"
      style={{ display: "block" }}
      data-ad-client="********"
      data-ad-slot="********"
      data-ad-format="auto"
      data-full-width-responsive="true"
    ></ins>
  );
}
```
